### PR TITLE
F/update module

### PR DESCRIPTION
**Pull request by yoesdinar**
update module to fix scurity

and update page to add vehicle

### CODE REVIEW

**Comment by bradwestfall** [comment]
Hi @yoesdinar, just curious why you added the PR but then closed it?

**Comment by yoesdinar** [comment]
hi @bradwestfall, Im sorry, I forked your repo to mine to learn about react and found that there are security issues in the repo. then I made a PR.

However, I just knew that my PR is going through your repo since I forked it. Before I thought my PR will going to mine. And I thought I was rude to make a PR without some deep thought in it,  and I dont know if you receive some PR or not haha.

So I closed it. I'm new to opensource world.

**Comment by bradwestfall** [comment]
Ah, no worries. By the way since I'm here at this repo I haven't visited in a while, just a heads up that React.createClass is old school and was replaced by real classes in React -- so learn those instead. That was around the end of 2015 or beginning of 2016 I think. Also, even though react classes are here to stay, there is new syntax just announced at [React Conf](https://www.youtube.com/playlist?list=PLPxbbTqCLbGE5AihOSExAa4wUM-P42EIJ) which we can use instead of classes but we don't have too (classes are here to stay). Since many of the features announced at React Conf are so new they are in alpha, I highly recommend just learning the class way first

**Comment by yoesdinar** [comment]
ah I see, thanks for your response and thanks also for the link. :D

**Pull request closed without merging**
